spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estudo
    username: teste
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  senha: MTIz
  expiracao: 3600000